### ISSUE TITLE
pengines GET, Url length, and idempotency

### ISSUE THREAD

**Issue by Anniepoo** [SWI-Prolog/packages-pengines#20]
pengine ASK is using HTTP GET as the underlying HTTP mechanism under PLTP.

This has a couple consequences for us:

1. GET is assumed idempotic.  Prolog queries are not.

We're concerned about seeing duplicate queries from the client.

2. GET query parameters have a maximum length, in practice. We're running into it. We're passing a 14K XML document back and forth.

http://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers

**Comment by rla** [comment]
+1

**Comment by JanWielemaker** [comment]
I fully agree.  Will add a POST version.  We can keep the GET version, so compatibility need not be
affected.

**Comment by JanWielemaker** [comment]
Added.  Not sure this is really the ideal yet.  Now encodes the format and id in the URL and the
event as POST payload using `Content-type: application/x-prolog`.  Might be better to access
/pengines/send/<id> and use the HTTP Accept header to specify the result format.  The old
GET is still supported.

Anyway, this is mostly internal.  Updated pengines.js and pengines.pl client to use the POST.

**Comment by Anniepoo** [comment]
What do we need to do on an application level, other than update our SWI-Prolog version?

**Comment by JanWielemaker** [comment]
Nothing.  Just update Prolog and make sure you get pengines.js from the Pengine server or
make a new copy (but I advice to always get it from the server you are talking to).
