### ISSUE TITLE
quasi_quotation_syntax/1 not sandboxed

### ISSUE THREAD

**Issue by Anniepoo** [SWI-Prolog/packages-pengines#26]
/* background program, defines a quasiquoter for piddle */

:- use_module(library(quasi_quotations)).
:- use_module(library(dcg/basics)).

:- quasi_quotation_syntax(piddle).

complains that quasi_quotation_syntax/1 isn't sandboxed

No permission to call sandboxed `'$set_predicate_attribute'(_6256/4,_6244,_6246)'
Reachable from:
	  quasi_quotation_syntax(A)

8c(

**Comment by JanWielemaker** [comment]
You have to pre-load code that contains dangerous directives.  You see the same in swish.pl,
preloading various libraries and renderers.
