### ISSUE TITLE
Pengine

### ISSUE THREAD

**Issue by NDE18** [SWI-Prolog/packages-pengines#31]
hello I am a program on Prolog that I then hosted on a server pengine [https://swish.swi-prolog.org], which worked normally. But, since yesterday when I load my web page my prolog program does not return anything. On the console of my browser I have this: 
XHR finished loading: OPTIONS "https://swish.swi-prolog.org/pengine/create".    jquery-2.1.3.min.js:4 
Please help me to solve this problem.
Thank you in advance.

**Comment by NDE18** [comment]
Here is the link of my app prolog [program](https://swish.swi-prolog.org/p/wallamres.pl)

**Comment by JanWielemaker** [comment]
If I run ?- main., it seems to do something.  Is this a program you run on a server of yours?  The
message seems more a server installation issue.   Please be precise.

**Comment by NDE18** [comment]
In fact, my program works when I run directly on the server online [https://swish.swi-prolog.org]. But he does not return anything when I call him from my web page. I used your example [https://github.com/SWI-Prolog/swish/blob/master/client/sin-table.html
].

**Comment by JanWielemaker** [comment]
Hard to say.  What about sharing the web page?  First step is probably to use the browser debugger and see what is happening.  There has been a recent change to pengines, but all tests and the interactive site still work fine.

**Comment by NDE18** [comment]
here is what the browser debugger displays:

Return value: undefined
copyOptions: ƒ copyOptions(to, from, list)
createOptions: {src_text: "↵:- include(wallamres).↵", format: "json", application: "swish", ask: "identify", chunk: 1000}
fillDefaultOptions: ƒ fillDefaultOptions(options)
options: {application: "swish", chunk: 1000, server: "https://swish.swi-prolog.org/pengine", ask: "identify", onoutput: ƒ, …}
src:["↵:- include(wallamres).↵"]
that: Pengine
      id: null
      options:{application: "swish", chunk: 1000, server: "https://swish.swi-prolog.org/pengine", ask: "identify", onoutput: ƒ, …}
      request: {readyState: 1, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
      _ proto__: Object

this: Pengine
       id: null
       options: {application: "swish", chunk: 1000, server: "https://swish.swi-prolog.org/pengine", ask: "identify", onoutput: ƒ, …}
       request: {readyState: 1, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
       __proto__:Object

**Comment by NDE18** [comment]
[My web application](msacad.com/wallamre)

**Comment by JanWielemaker** [comment]
I have a clue, but only a vague one.  Working on it.

**Comment by NDE18** [comment]
Thank you.


2018-02-16 14:39 GMT+01:00 Jan Wielemaker <notifications@github.com>:

**Comment by JanWielemaker** [comment]
Ok, pushed a fix, updated swish.  All seems working again, including your application.

**Comment by NDE18** [comment]
Thank you very much, it works very well. Please what was the problem?

**Comment by JanWielemaker** [comment]
Wrong argument order inside the pengines library after a rewrite and not passing the resulting error to the browser.

**Comment by NDE18** [comment]
Thank you God bless you.
