### ISSUE TITLE
Inconsistent and unexplained terminology

### ISSUE THREAD

**Issue by triska** [SWI-Prolog/packages-pengines#32]
Please compare for example the descriptions of [`pengine_input/2`](http://eu.swi-prolog.org/pldoc/doc_for?object=pengine_input/2) and [`pengine_respond/3`](http://eu.swi-prolog.org/pldoc/doc_for?object=pengine_respond/3):

One "Sends Prompt to the **parent** pengine", the other "Sends a response ... to a **slave** pengine that has prompted its **master** for input".

In [`pengine_create/1`](http://eu.swi-prolog.org/pldoc/doc_for?object=pengine_create/1), we find that "slave pengine" is synonymous with "child", but nowhere is it mentioned that "master" is (presumably) synonymous with "parent".

If possible, please use consistent terminology, or at least explain the terminology up front. Thank you!

**Comment by torbjornlager** [comment]
Thanks! To consistently use one pair of terms over the other would have introduced a LOT of changes in either pendoc.md or in pengines.pl so we explained that the master/slave and parent/child are synonyms and also added clarifying text in the docs for pengine_input/2 and pengine_respond/3.

**Comment by triska** [comment]
Thank you! I consider this suboptimal.
