### ISSUE TITLE
Safety of pengine_input/2,  pengine_output/1 and pengine_debug/2

### ISSUE THREAD

**Issue by triska** [SWI-Prolog/packages-pengines#33]
I have now several times run into the following issue:

Using `pengine_output/1` and `pengine_input/2` requires `library(pengines_sandbox)`, which states:

<blockquote>
This module can be  loaded  alongside   library(pengines)  to  allow for
calling remote pengines from a sandboxed environment. This is disallowed
by default because one of the  use-cases   of  sandboxed  pengines is to
provide a generic application interface. In such   cases you do not want
the application to act as a proxy, in particular not to other systems in
a protected network.
</blockquote>

This makes perfect sense. However, is it  justified to require this for:

- `pengine_output/1`
- `pengine_input/2`
- `pengine_debug/2` ?

If safely possible, I would appreciate if these predicates could be more easily used in applications by not requiring loading `library(pengines_sandbox)`.

Thank you!

**Comment by JanWielemaker** [comment]
Right.  Pushed 1226e9c7ceb9b359908702e8a2ac5c615f4e658b to fix this
