### ISSUE TITLE
pengines_io does not support flush_output/0

### ISSUE THREAD

**Issue by triska** [SWI-Prolog/packages-pengines#37]
Let `server.pl` consist of the following code:

<pre>
:- module(server, []).

:- use_module(library(pengines)).
:- use_module(library(http/thread_httpd)).
:- use_module(library(http/http_dispatch)).
:- use_module(library(http/http_server_files)).
:- use_module(library(http/http_files)).
:- use_module(library(http/http_unix_daemon)).

:- pengine_application(myapp).
:- use_module(myapp:library(pengines_io)).
pengines:prepare_module(Module, myapp, _Options) :-
        pengines_io:pengine_bind_io_to_html(Module).

myapp:pred :-
        format("pred\n", []).

:- http_handler(/, http_reply_from_files(., []), [prefix]).
</pre>

Let `demo.html` consist of:

<pre>
&lt;!DOCTYPE html&gt;
&lt;html lang="en"&gt;
  &lt;head&gt;
    &lt;title&gt;Demo&lt;/title&gt;
    &lt;script src="js/pengines.js"&gt;&lt;/script&gt;
  &lt;/head&gt;
  &lt;body style="padding-left: 5%; padding-right: 5%"&gt;
    &lt;br&gt;&lt;br&gt;
    
    &lt;script&gt;
    var p = new Pengine({
        oncreate: function () { p.ask('pred'); },
        onoutput: function () { console.log(this.data); },
        application: "myapp",
        server: "pengine",
    });

    &lt;/script&gt;
  &lt;/body&gt;
&lt;/html&gt;
</pre>

Start the server with:

    $ swipl server.pl --port=5055 --interactive

and direct your browser to `http://localhost:5055/demo.html`.

If everything works, you see in the JavaScript **console**:

<pre>
&lt;pre class="console"&gt;
pred
&lt;/pre&gt;
</pre>

This means that `pengines_io` has done its job, because the output is decorated.

In contrast, if we change the definition of `myapp:pred/0` to:

<pre>
myapp:pred :-
        format("pred\n", []),
        <b>flush_output</b>.
</pre>

Then we get:

<pre>
<b>No permission to call sandboxed `flush_output'</b>
Reachable from:
	  '93592351277906267204527080385574986579':pred
</pre>

From the source of `pengines_io`, it seems that support for `flush_output` is intended. However, it seems as if it does not work.

**Comment by JanWielemaker** [comment]
In the meanwhile this was emulated, but not properly declared.  Fixed.   Submodules may do output in recent versions as the current output stream is redefined.
