### ISSUE TITLE
Xpce Emacs does not automatically cross-reference pengines.pl

### ISSUE THREAD

**Issue by xpxaxsxi** [SWI-Prolog/packages-pengines#51]
First I thought this was some error in code, then I figured that the cross-referencer does not work. After I press F5 I get proper colors and stuff. 

I have been accepting that those scandinavian characters are being rendered badly, but now I noticed that the Github file doesn't have those bad characters. So this could be an issue with my Swi-Prolog settings. 

Now that I payed serious attention to those bad chars, I found out that Firefox and Notepad open pengines.pl properly, but WordPad has those bad chars.

![kuva](https://user-images.githubusercontent.com/10254876/73384691-6ac4be00-42d4-11ea-9459-f8d4b635ca35.png)

problem is being caused by UTF-8 bytes being interpreted as Windows-1252 (or ISO 8859-1) byte

![kuva](https://user-images.githubusercontent.com/10254876/73387582-6fd83c00-42d9-11ea-865c-d51072b3ed75.png)

**Comment by xpxaxsxi** [comment]
This is what my Emacs says about properties
![kuva](https://user-images.githubusercontent.com/10254876/73388294-a82c4a00-42da-11ea-832a-5308c4830bca.png)

**Comment by JanWielemaker** [comment]
This has nothing to do with Pengines.  In the PceEmacs code we find

```
class_variable(auto_colourise_size_limit, int, 100000,
               "Auto-colourise if buffer is smaller then this").
```

Which you can override in the xpce/Defaults file using for example

     emacs_prolog_mode.auto_colourise_size_limit: 1000000

As is though, xpce isn't multi-threaded and putting some limit on it avoids the editor being blocked for a long time while cross-referencing and colouring a buffer.

**Comment by xpxaxsxi** [comment]
Ok. I was learning about Pengines by reading the [Swi-Prolog site](https://www.swi-prolog.org/pldoc/doc/_SWI_/library/pengines.pl) and doing some own programming, as in learning by doing. 

Maybe the bad characters could be fixed in the library(pengines) prolog file? I was making mistakes and began to think that the pengines-library could have problems, no, I had problems. 

Also the url at [this page](https://www.swi-prolog.org/pldoc/doc/_SWI_/library/pengines.pl), should refer to https://www.swi-prolog.org/pldoc/doc_for?object=section(%27packages/pengines.html%27) Now it refers to same page.
![kuva](https://user-images.githubusercontent.com/10254876/73553632-eba9c400-4452-11ea-91ba-db187e823899.png)
