### ISSUE TITLE
"ssl3_get_server_certificate: certificate verify failed" for https://pengines.swi-prolog.org

### ISSUE THREAD

**Issue by Alex4224** [SWI-Prolog/packages-pengines#52]
I am trying the examples from the pengines [documentation](https://www.swi-prolog.org/pldoc/man?section=pengine-examples), but I get the following error when doing pengine_create with server('https://pengines.swi-prolog.org') or pengine_rpc (depending on the example):

ERROR: SSL(14090086) ssl3_get_server_certificate: certificate verify failed

Here are the version infos:
SWI-Prolog version 7.2.3 for amd64
Linux xxxx 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux
swi-prolog:
  Installed: 7.2.3+dfsg-6

The website was not down when I tried it (and I don't get any errors form my browser when visiting it), the online example (scratchpad etc) were working.

I did "update-ca-certificates" successfully but it didn't do anything.

**Comment by JanWielemaker** [comment]
7.2.3 is a really old version ...   I'd first try updating to 8.2.4 or 8.3.18.   This should work just fine.

**Comment by Alex4224** [comment]
I can confirm that the issue is gone after upgrading to 8.0.2
I upgraded from 9 (stretch) to 10 (buster). It is possible that the issue was coming from another debian package related to ssl certificates.
7.2.3 was the version packaged with stretch, which is indeed pas its end of life point; though its LTS end of life is supposed to be in 2022. 
Thank you.

**Comment by JanWielemaker** [comment]
The SWI-Prolog SSL interface has also gone through major revisions since 7.2.   Debian used to be really slow picking following SWI-Prolog's releases.   Luckily this has improved a lot.   Still, you better use 8.2.x or even 8.3.x rather than 8.0 for serious applications.    Compiling yourself is not hard and there are also Docker as well as snap images.
