### ISSUE TITLE
write_term/2: nl(true) Option Is Ignored

### ISSUE THREAD

**Issue by nbcarey** [SWI-Prolog/packages-pengines#54]
The predicate `write_term/2` appears to ignore (at least) the `nl(true)` option.

**Steps To Reproduce**
See test case at https://swish.swi-prolog.org/p/BfGWbyLR.pl
```prolog
test_case :-
  writeln('-----'),
  write_term( 1 + 2 , [ nl(true) ] ),
  writeln('-----').
```

**Expected Output:**
```
-----
1+2
-----
```

**Actual Output:**
```
-----
1+2-----
```

**Comment by JanWielemaker** [comment]
The Pengine system has its own implementation of write_term/2 to emit HTML.   That implementation is probably incomplete.  Patch 3713df49bc8b3bd707bb4574589b8cbc6c8b8d71 adds the `full_stop` and `nl` options.   Public SWISH will be updated the next time its Prolog version is updated.
